### ISSUE TITLE
Consider renaming default branch to `main`

### ISSUE THREAD

**Issue by tclune** [fortran-lang/fortran-lang.org#338] opened 2021-09-24 17:29 UTC
Just a socially conscious recommendation.

https://github.com/github/renaming

**Comment by certik** [comment] 2021-09-24 17:38
Thanks. We considered that and renamed other repositories. But with this one we need to do quite a few fixes:

https://github.com/fortran-lang/fortran-lang.org/search?q=master

However if you send us PRs, it can happen faster. :)

**Comment by awvwgk** [comment] 2021-09-24 18:48
Duplicate of https://github.com/fortran-lang/fortran-lang.org/issues/325

**Comment by awvwgk** [comment] 2022-08-06 09:31
This repository will be migrated to https://github.com/fortran-lang/webpage soon (see #415), where we use *main* as name for the default branch.

**Closed by awvwgk** 2022-08-06 09:31 UTC
Labels: duplicate
