### ISSUE TITLE
Duplicates of M_CLI and M_CLI2 in the fpm registry page

### ISSUE THREAD

**Issue by vmagnin** [fortran-lang/fortran-lang.org#239] opened 2021-04-06 17:31 UTC
In the fpm registry page (https://fortran-lang.org/packages/fpm), I have found that there is duplicates of :

- M_CLI
- M_CLI2

It seems to be due to the fact that in the links there is one `M_CLI` and one `M_cli` (lowercase). Same for `M_CLI2` and  `M_cli2`.

Suggestion: with an alphabetical sort those problems could be more visible.

**Comment by awvwgk** [comment] 2021-04-06 18:19
Duplicate of https://github.com/fortran-lang/fpm-registry/issues/31

**Comment by awvwgk** [comment] 2022-08-06 09:37
Resolved with https://github.com/fortran-lang/fpm-registry/pull/38

**Closed by awvwgk** 2022-08-06 09:37 UTC
Labels: packages
