### ISSUE TITLE
XML file without style

### ISSUE THREAD

**Issue by aslozada** [fortran-lang/fortran-lang.org#195] opened 2021-02-05 17:13 UTC
Hi,

The link _news_, in navbar class, returns a XML file without style.

------------------------------------------------------------------------------------------------------------------------------------------------------------
This XML file does not appear to have any style information associated with it. The document tree is shown below.

<feed xmlns="http://www.w3.org/2005/Atom">
<title type="text" xml:lang="en">Fortran Newsletter</title>
<link type="application/atom+xml" href="https://fortran-lang.org/news.xml" rel="self"/>
<link type="text" href="https://fortran-lang.org/news" rel="alternate"/>
<updated>2021-02-02T22:08:53+00:00</updated>
<id>/news</id>

**Comment by milancurcic** [comment] 2021-02-05 17:26
Hi @aslozada, is there any part of the website that doesn't seem to work correctly? I can't find it. How do I reproduce the issue?

**Comment by aslozada** [comment] 2021-02-05 17:31
In the navbar, the link _news_, https://fortran-lang.org/news.xml, returns a XML file without style.

**Comment by LKedward** [comment] 2021-02-05 17:33
Hi @aslozada, are you referring to the RSS feed link?

**Comment by aslozada** [comment] 2021-02-05 17:35
Yes. In the "button" of RSS.

**Comment by LKedward** [comment] 2021-02-05 17:37
Ah okay, the xml file that it links to is intended to be read by an RSS reader and hence it will not display properly in a Web browser.

**Comment by awvwgk** [comment] 2021-02-21 15:55
I'll close this issue as resolved.

**Closed by awvwgk** 2021-02-21 15:55 UTC
