### ISSUE TITLE
Intel compiler info needs to be updated on website

### ISSUE THREAD

**Issue by ElAlderson** [fortran-lang/fortran-lang.org#185] opened 2020-12-19 11:35 UTC
Intel Parallel Studio XE has been rebranded to [Intel oneAPI](https://software.intel.com/content/www/us/en/develop/tools/oneapi/commercial-base-hpc.html) which now contains two FORTRAN compilers: Intel FORTRAN Compiler Classic (`ifort`) and Intel FORTRAN Compiler Beta (`ifx`). [Choosing a compiler](https://fortran-lang.org/learn/os_setup/choose_compiler) and [Fortran Compilers](https://fortran-lang.org/compilers/) pages need to be updated accordingly.

**Comment by LKedward** [comment] 2020-12-19 11:51
Duplicate of #181

**Comment by LKedward** [comment] 2020-12-19 11:53
Bonsoir @ElAlderson, thanks for reporting 👍

**Comment by ElAlderson** [comment] 2020-12-19 16:43
> 
> 
> Bonsoir @ElAlderson, thanks for reporting 👍

No problem!

**Closed** 2020-12-19 20:06 UTC
